### ISSUE TITLE
Getting an error when no initial URI

### ISSUE THREAD

**Issue by alexrait** [avioli/uni_links#7] opened 2018-08-29 11:06 UTC
Both for Android and for IOS, I get this:
"Unhandled exception:
NoSuchMethodError: The getter 'host' was called on null

It appears in the verbose log.

Can I check somehow the way the application was started and then use the corresponding method?

**Comment by avioli** [comment] 2018-09-05 14:35
Could you give me more information, so I can reproduce this?

The plugin doesn't have a "host" getter, nor any of the native modules, but [Uri](https://docs.flutter.io/flutter/dart-core/Uri/Uri.html) does.

If you call `getInitialUri()` you might get a `null`. Same goes with `getUriLinksStream()` - it could produce `null` values. In such cases you could either check if it is null or guard like this:

```dart
Uri uri = null; // we simulate a null Uri
print(uri?.host); // this prints null
```

**Comment by avioli** [comment] 2018-09-25 12:58
@alexrait: Did you manage to sort this out?

**Comment by avioli** [comment] 2018-09-27 01:58
I'm going to close this ticket, since I'm guessing the OP doesn't have an issue anymore.

**Closed by avioli** 2018-09-27 01:58 UTC
Labels: question
